# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '3'
services:
   selenium-hub:
      image: selenium/hub:3.141.59-20210929
      container_name: selenium-hub
      ports:
      - 4444:4444

   chrome:
      image: selenium/node-chrome:3.141.59-20210929
      volumes:
      - /dev/shm:/dev/shm
      depends_on:
      - selenium-hub
      environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

   firefox:
      image: selenium/node-firefox:3.141.59-20210929
      volumes:
      - /dev/shm:/dev/shm
      depends_on:
      - selenium-hub
      environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

   database:
      image: postgres
      container_name: database
      environment:
         POSTGRES_PASSWORD: postgres
      volumes:
      - ./database/init.d:/docker-entrypoint-initdb.d/
      ports:
      - 5432:5432

   rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      volumes:
      - ./rabbitmq/:/var/lib/rabbitmq/mnesia/:rw
      ports:
      - 8082:15672
      - 5672:5672