version: '3'

services:   
   database:
      image: postgres      
      container_name: database
      environment:
         POSTGRES_PASSWORD: postgres
      volumes:
      - ./database/init.d:/docker-entrypoint-initdb.d/
      ports:
         - 5432:5432
   adminer:
      image: adminer
      container_name: adminer
      ports:
      - 8089:8080
   rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      volumes:
         - ./rabbitmq/:/var/lib/rabbitmq/mnesia/:rw
      ports:
       - 8082:15672
       - 5672:5672   
   alta:
     build:
        context: ./poc-excecoes-alta-baixa-simulador-alta
        dockerfile: Dockerfile
     container_name: alta
     ports:
        - 8080:8080
     links:
        - database
        - rabbitmq
   baixa:
      build:
         context: ./poc-excecoes-alta-baixa-simulador-baixa
         dockerfile: Dockerfile
      container_name: baixa
      links:
         - database
         - rabbitmq
   dlq_processor:
      build:
         context: ./poc-excecoes-alta-baixa-dlq-processor
         dockerfile: Dockerfile
      container_name: dlq_processor
      links:
       - rabbitmq
   parking_lot_processor:
      container_name: pkng_lot_processor
      build:
         context: ./poc-excecoes-alta-baixa-pkng-lot-processor
         dockerfile: Dockerfile