CREATE TABLE informacao (
	info_id integer GENERATED BY default AS IDENTITY,
	dados varchar(4096) NOT NULL,
	data_criacao timestamp NOT NULL,
	data_atualizacao timestamp,
	PRIMARY KEY(info_id)
);

CREATE TABLE sub_informacao (
	sub_info_id integer GENERATED BY default AS IDENTITY,
	info_id integer NOT NULL,
	sub_dados varchar(4096) NOT NULL,
	data_criacao timestamp NOT NULL,
	data_atualizacao timestamp,
	PRIMARY KEY(sub_info_id),
	FOREIGN KEY(info_id) REFERENCES informacao(info_id)
);